name: Expo Cloud Build for Local Download

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 5. Verify authentication
      - name: Verify Expo login
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 6. Build Android
      - name: Build Android
        run: eas build --platform android --non-interactive --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 7. Build iOS (only on macOS)
      - name: Build iOS
        if: runner.os == 'macOS'
        run: eas build --platform ios --non-interactive --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 8. Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-build
          path: |
            Frontend/**/*.apk
            Frontend/**/*.aab
            Frontend/**/*.ipa
