name: Expo Cloud Build for Local Download

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install expo-cli
      - name: Install expo-cli
        run: npm install -g expo-cli

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 6. Authenticate with Expo using token
      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      # 7. Build Android
      - name: Build Android
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --non-interactive --profile production

      # 8. Build iOS (only on macOS runners)
      - name: Build iOS
        if: runner.os == 'macOS'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --non-interactive --profile production

      # 9. Upload APK/IPA artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-build
          path: |
            Frontend/**/*.apk
            Frontend/**/*.aab
            Frontend/**/*.ipa
